exports.participants = [
	{
		name: 'Sara Svensson',
		email: 'sarasvensson@gmail.com',
		phone: '0739440022',
		role: 'FOLLOWER',
		paymentpending: '-',
	},
	{
		name: 'Sara Eriksson',
		email: 'saraeriksson@gmail.com',
		phone: '0739440022',
		role: 'FOLLOWER',
		paymentpending: '-',
	},
	{
		name: 'Lisa Svensson',
		email: 'lisasvensson@gmail.com',
		phone: '0739440021',
		role: 'FOLLOWER',
		paymentpending: '-',
	},
	{
		name: 'Mia Bro',
		email: 'miabro@gmail.com',
		phone: '0739440000',
		role: 'FOLLOWER',
		paymentpending: '-',
	},
	{
		name: 'Fia Boman',
		email: 'fiaboman@gmail.com',
		phone: '0739440025',
		role: 'FOLLOWER',
		paymentpending: '-',
	},
	{
		name: 'Ann-Louise Bjork',
		email: 'bjorken@gmail.com',
		phone: '0739449133',
		role: 'FOLLOWER',
		paymentpending: '-',
	},
	{
		name: 'Fia Larsson',
		email: 'fia@gmail.com',
		phone: '0709490033',
		role: 'FOLLOWER',
		paymentpending: '-',
	},
	{
		name: 'Linnea Roos',
		email: 'roos@gmail.com',
		phone: '0739440765',
		role: 'FOLLOWER',
		paymentpending: '-',
	},
	{
		name: 'Sara Davidsson',
		email: 'sarad@gmail.com',
		phone: '0739440099',
		role: 'FOLLOWER',
		paymentpending: '-',
	},
	{
		name: 'Linn Boman',
		email: 'linn@gmail.com',
		phone: '0739440088',
		role: 'FOLLOWER',
		paymentpending: '-',
	},
	{
		name: 'Sven Svensson',
		email: 'svensvensson@gmail.com',
		phone: '0730001111',
		role: 'LEADER',
		paymentpending: '-',
	},
	{
		name: 'Bror Eriksson',
		email: 'eriksson@gmail.com',
		phone: '0709693312',
		role: 'LEADER',
		paymentpending: '-',
	},
	{
		name: 'Leo Eriksson',
		email: 'leo@gmail.com',
		phone: '0709693312',
		role: 'LEADER',
		paymentpending: '-',
	},
	{
		name: 'Daniel Persson',
		email: 'daniel@gmail.com',
		phone: '0709693677',
		role: 'LEADER',
		paymentpending: '-',
	},
	{
		name: 'Leopold Davidsson',
		email: 'leopold@gmail.com',
		phone: '0739693312',
		role: 'LEADER',
		paymentpending: '-',
	},
	{
		name: 'Sebastian Oswald',
		email: 'sebbos@gmail.com',
		phone: '0769696612',
		role: 'LEADER',
		paymentpending: '-',
	},
	{
		name: 'Emil Persson',
		email: 'emilpsson@gmail.com',
		phone: '0766693312',
		role: 'LEADER',
		paymentpending: '-',
	},
	{
		name: 'Johan Malmgren',
		email: 'malmgren@gmail.com',
		phone: '0769693218',
		role: 'LEADER',
		paymentpending: '-',
	},
	{
		name: 'Rick Visser',
		email: 'rick@gmail.com',
		phone: '0739693313',
		role: 'LEADER',
		paymentpending: '-',
	},
	{
		name: 'Tim Lundgren',
		email: 'lundgrens@gmail.com',
		phone: '0739333312',
		role: 'LEADER',
		paymentpending: '-',
	},
]
