exports.springTerm2023 = [
	{
		namn: 'Bachata Nybörjare',
		dansstil: 'Bachata',
		start: '2023-01-30',
		slutar: '2023-04-03',
		tid: '18:00',
		klasstidIMinuter: 60,
		pris: 1500,
		klassLedare: ['Leo', 'Lisette'],
		totalLeaders: 1,
		totalFollowers: 0,
		totalParticipants: 1,
		participants: [
			{
				name: 'Sven Svensson',
				contact: '0739678787',
				role: 'LEADER',
				paymentpending: true,
			},
		],
	},
	{
		namn: 'Bachata Fortsättning',
		dansstil: 'Bachata',
		start: '2023-01-30',
		slutar: '2023-04-03',
		tid: '19:00',
		klasstidIMinuter: 90,
		pris: 2000,
		klassLedare: ['Leo', 'Lisette'],
		totalLeaders: 1,
		totalFollowers: 1,
		totalParticipants: 2,
		participants: [
			{
				_id: '8459834588',
				name: 'Erik Eriksson',
				contact: '0739678790',
				role: 'LEADER',
				paymentpending: true,
			},
			{
				_id: '8459834590',
				name: 'Erika Sten',
				contact: '0739898790',
				role: 'FOLLOWER',
				paymentpending: true,
			},
		],
	},
	{
		namn: 'Bachata Avancerad',
		dansstil: 'Bachata',
		start: 2023 - 01 - 31,
		slutar: 2023 - 04 - 04,
		tid: '18:00',
		klasstidIMinuter: 90,
		pris: 2000,
		klassLedare: ['Leo', 'Lisette'],
		totalLeaders: 0,
		totalFollowers: 0,
		totalParticipants: 0,
		participants: [
			{
				name: '',
				contact: '',
				role: '',
				paymentpending: true,
			},
		],
	},
	{
		namn: 'LA Salsa Nybörjare',
		dansstil: 'LA Salsa',
		start: '2023-01-31',
		slutar: '2023-04-04',
		tid: '19:30',
		klasstidIMinuter: 60,
		pris: 1500,
		klassLedare: ['Leo', 'Lisette'],
		totalLeaders: 0,
		totalFollowers: 0,
		totalParticipants: 0,
		participants: [
			{
				name: '',
				contact: '',
				role: '',
				paymentpending: true,
			},
		],
	},
	{
		namn: 'LA Salsa Fortsättning',
		dansstil: 'LA Salsa',
		start: 2023 - 02 - 01,
		slutar: 2023 - 04 - 05,
		tid: '18:00',
		klasstidIMinuter: 90,
		pris: 2000,
		klassLedare: ['Andreas', 'Inka'],
		totalLeaders: 0,
		totalFollowers: 0,
		totalParticipants: 0,
		participants: [
			{
				name: '',
				contact: '',
				role: '',
				paymentpending: true,
			},
		],
	},
	{
		namn: 'LA Salsa Avancerad',
		dansstil: 'LA Salsa',
		start: '2023-02-01',
		slutar: '2023-04-05',
		tid: '19:30',
		klasstidIMinuter: 90,
		pris: 2000,
		klassLedare: ['Andreas', 'Inka'],
		totalLeaders: 0,
		totalFollowers: 0,
		totalParticipants: 0,
		participants: [
			{
				name: '',
				contact: '',
				role: '',
				paymentpending: true,
			},
		],
	},
	{
		namn: 'Kubansk Salsa Nybörjare',
		dansstil: 'Kubansk Salsa',
		start: '2023-02-02',
		slutar: '2023-04-06',
		tid: '17:30',
		klasstidIMinuter: 60,
		pris: 1500,
		klassLedare: ['Andreas', 'Inka'],
		totalLeaders: 0,
		totalFollowers: 0,
		totalParticipants: 0,
		participants: [
			{
				name: '',
				contact: '',
				role: '',
				paymentpending: true,
			},
		],
	},
	{
		namn: 'Kubansk Salsa Fortsättning',
		dansstil: 'Kubansk Salsa',
		start: '2023-02-02',
		slutar: '2023-04-06',
		tid: '18:30',
		klasstidIMinuter: 90,
		pris: 2000,
		klassLedare: ['Andreas', 'Inka'],
		totalLeaders: 0,
		totalFollowers: 0,
		totalParticipants: 0,
		participants: [
			{
				name: '',
				contact: '',
				role: '',
				paymentpending: true,
			},
		],
	},
	{
		namn: 'Kubansk Salsa Avancerad',
		dansstil: 'Kubansk Salsa',
		start: '2023-02-02',
		slutar: '2023-04-06',
		tid: '20:00',
		klasstidIMinuter: 90,
		pris: 2000,
		klassLedare: ['Andreas', 'Inka'],
		totalLeaders: 0,
		totalFollowers: 0,
		totalParticipants: 0,
		participants: [
			{
				name: '',
				contact: '',
				role: '',
				paymentpending: true,
			},
		],
	},
]
